// Reálné názvy z Vinohrad a navazujícího širšího centra Prahy.
// Zdroj: OpenStreetMap / Overpass, výběr v okruhu 1,5 km od Vinohrad.
window.VINOHRADY_STREETS = [
  'Americká','Anglická','Anny Letenské','Apolinářská','Balbínova','Baranova',
  'Bartoškova','Bělehradská','Belgická','Benátská','Blahníkova','Blanická',
  'Blodkova','Boleslavova','Boleslavská','Bolzanova','Bořivojova','Borodinská',
  'Botičská','Boženy Němcové','Božetěchova','Bruselská','Budečská','Bulharská',
  'Čajkovského','Čerchovská','Čermákova','Černá','Černomořská','Čestmírova',
  'Charkovská','Chelčického','Chlumova','Chodská','Chopinova','Chorvatská',
  'Chvalova','Čiklova','Cimburkova','Ctiborova','Ctiradova','Dalimilova',
  'Dánská','Dlážděná','Donská','Dudova','Dykova','Estonská','Fibichova','Finská',
  'Francouzská','Fričova','Hálkova','Havlíčkova','Helénská','Hlavova','Holandská',
  'Horská','Hradešínská','Husinecká','Husitská','Hybernská','Ibsenova','Italská',
  'Jagellonská','Jana Masaryka','Jaromírova','Ječná','Jenštejnská','Jeronýmova',
  'Jeruzalémská','Ježkova','Jindřišská','Jugoslávská','Jungmannova','Kateřinská',
  'Ke Karlovu','Kladská','Kodaňská','Kolínská','Koperníkova','Korčákova','Korunní',
  'Košická','Koubkova','Kozácká','Krakovská','Krásova','Křemencova','Křesomyslova',
  'Křišťanova','Křížkovského','Krkonošská','Krymská','Kubelíkova','Kunětická',
  'Laubova','Lazarská','Legerova','Libická','Lichnická','Lipanská','Lípová',
  'Londýnská','Lublaňská','Lucemburská','Lužická','Máchova','Madridská',
  'Magdalény Rettigové','Malá Štěpánská','Mánesova','Mečislavova','Melounová',
  'Mexická','Mezibranská','Mikovcova','Milešovská','Milíčova','Mnatova','Mojmírova',
  'Moravská','Moskevská','Mužíkova','Myslíkova','Na Bojišti','Na Fidlovačce',
  'Na Florenci','Na Folimance','Na Hrádku','Na Kleovce','Na Kovárně','Na Kozačce',
  'Na Královce','Na Moráni','Na Můstku','Na Ostrůvku','Na Příkopě','Na Rybníčku',
  'Na Šafránce','Na Slovanech','Na Slupi','Na Smetance','Na Stráni','Na Švihance',
  'Na Vítězné pláni','Na Zámecké','Na Zbořenci','Na Zderaze','Nad Petruskou',
  'Národní','Národní třída','Navrátilova','Nekázanka','Nezamyslova','Nitranská',
  'Norská','Novgorodská','Nuselská','Oblouková','Odborů','Oldřichova','Olivova',
  'Omladinářů','Ondříčkova','Opatovická','Opletalova','Orebitská','Orelská','Orlická',
  'Ostrovní','Otakarova','Palackého','Panská','Perlová','Perucká','Perunova',
  'Petra Rezka','Petrohradská','Pod Karlovem','Pod Nuselskými schody','Pod Slovany',
  'Pod Stupni','Pod Terebkou','Pod Větrovem','Pod Výtopnou','Pod Zvonařkou',
  'Politických vězňů','Polská','Pospíšilova','Přemyslovská','Příběnická',
  'Přibyslavská','Příčná','Provaznická','Prvního pluku','Purkyňova','Radhošťská',
  'Řehořova','Rejskova','Resslova','Řeznická','Římská','Řipská','Rokycanova',
  'Rostislavova','Rostovská','Rubešova','Rumunská','Ruská','Růžová','Rybalkova',
  'Šafaříkova','Salmovská','Sámova','Sarajevská','Sázavská','Seifertova','Sekaninova',
  'Senovážná','Sevastopolská','Ševčíkova','Sezimova','Školská','Škrétova','Slavíkova',
  'Slezská','Slovenská','Šmilovského','Smolenská','Sobotecká','Sokolská','Spálená',
  'Španělská','Sportovní','Spytihněvova','Štěpánská','Štítného','Studničkova',
  'Šubertova','Šumavská','Svatoplukova','Svobodova','Táboritská','Táborská',
  'Třebízského','Trocnovská','Trojanova','Trojická','Tyršova','U Bulhara','U Divadla',
  'U Havlíčkových sadů','U Horské brány','U Kanálky','U Nemocnice','U Památníku',
  'U Pernštejnských','U Půjčovny','U Rajské zahrady','U Staré sokolovny','U Tržnice',
  'U Viktorie','U Vodárny','U Vršovického nádraží','U Zvonařky','Ukrajinská',
  'Uruguayská','V Celnici','V Cípu','V Jámě','V Jirchářích','V Tůních','Václavská',
  'Varšavská','Ve Smečkách','Velehradská','Větrov','Vinařického','Viničná',
  'Vinohradská','Víta Nejedlého','Vladimírova','Vladislavova','Vlastislavova',
  'Vlkova','Vocelova','Vodičkova','Voroněžská','Votočkova','Vozová','Vršovická',
  'Vyšehradská','Washingtonova','Wenzigova','Wilsonova','Záhřebská','Žateckých',
  'Závišova','Žitná','Žitomírská','Zvonařova','Albertov','FÃ¼gnerovo náměstí',
  'I. P. Pavlova','Karlovo náměstí','Kostnické náměstí','náměstí Bratří Synků',
  'náměstí Generála Kutlvašra','náměstí I. P. Pavlova','náměstí Jiřího z Poděbrad',
  'náměstí Míru','Ostrčilovo náměstí','Senovážné náměstí','Škroupovo náměstí',
  'Sladkovského náměstí','Tylovo náměstí','Vršovické náměstí','Žižkovo náměstí'
];
