// ReÃ¡lnÃ© nÃ¡zvy z Vinohrad a navazujÃ­cÃ­ho Å¡irÅ¡Ã­ho centra Prahy.
// Zdroj: OpenStreetMap / Overpass, vÃ½bÄ›r v okruhu 1,5 km od Vinohrad.
window.VINOHRADY_STREETS = [
  'AmerickÃ¡','AnglickÃ¡','Anny LetenskÃ©','ApolinÃ¡Å™skÃ¡','BalbÃ­nova','Baranova',
  'BartoÅ¡kova','BÄ›lehradskÃ¡','BelgickÃ¡','BenÃ¡tskÃ¡','BlahnÃ­kova','BlanickÃ¡',
  'Blodkova','Boleslavova','BoleslavskÃ¡','Bolzanova','BoÅ™ivojova','BorodinskÃ¡',
  'BotiÄskÃ¡','BoÅ¾eny NÄ›mcovÃ©','BoÅ¾etÄ›chova','BruselskÃ¡','BudeÄskÃ¡','BulharskÃ¡',
  'ÄŒajkovskÃ©ho','ÄŒerchovskÃ¡','ÄŒermÃ¡kova','ÄŒernÃ¡','ÄŒernomoÅ™skÃ¡','ÄŒestmÃ­rova',
  'CharkovskÃ¡','ChelÄickÃ©ho','Chlumova','ChodskÃ¡','Chopinova','ChorvatskÃ¡',
  'Chvalova','ÄŒiklova','Cimburkova','Ctiborova','Ctiradova','Dalimilova',
  'DÃ¡nskÃ¡','DlÃ¡Å¾dÄ›nÃ¡','DonskÃ¡','Dudova','Dykova','EstonskÃ¡','Fibichova','FinskÃ¡',
  'FrancouzskÃ¡','FriÄova','HÃ¡lkova','HavlÃ­Äkova','HelÃ©nskÃ¡','Hlavova','HolandskÃ¡',
  'HorskÃ¡','HradeÅ¡Ã­nskÃ¡','HusineckÃ¡','HusitskÃ¡','HybernskÃ¡','Ibsenova','ItalskÃ¡',
  'JagellonskÃ¡','Jana Masaryka','JaromÃ­rova','JeÄnÃ¡','JenÅ¡tejnskÃ¡','JeronÃ½mova',
  'JeruzalÃ©mskÃ¡','JeÅ¾kova','JindÅ™iÅ¡skÃ¡','JugoslÃ¡vskÃ¡','Jungmannova','KateÅ™inskÃ¡',
  'Ke Karlovu','KladskÃ¡','KodaÅˆskÃ¡','KolÃ­nskÃ¡','KopernÃ­kova','KorÄÃ¡kova','KorunnÃ­',
  'KoÅ¡ickÃ¡','Koubkova','KozÃ¡ckÃ¡','KrakovskÃ¡','KrÃ¡sova','KÅ™emencova','KÅ™esomyslova',
  'KÅ™iÅ¡Å¥anova','KÅ™Ã­Å¾kovskÃ©ho','KrkonoÅ¡skÃ¡','KrymskÃ¡','KubelÃ­kova','KunÄ›tickÃ¡',
  'Laubova','LazarskÃ¡','Legerova','LibickÃ¡','LichnickÃ¡','LipanskÃ¡','LÃ­povÃ¡',
  'LondÃ½nskÃ¡','LublaÅˆskÃ¡','LucemburskÃ¡','LuÅ¾ickÃ¡','MÃ¡chova','MadridskÃ¡',
  'MagdalÃ©ny RettigovÃ©','MalÃ¡ Å tÄ›pÃ¡nskÃ¡','MÃ¡nesova','MeÄislavova','MelounovÃ¡',
  'MexickÃ¡','MezibranskÃ¡','Mikovcova','MileÅ¡ovskÃ¡','MilÃ­Äova','Mnatova','MojmÃ­rova',
  'MoravskÃ¡','MoskevskÃ¡','MuÅ¾Ã­kova','MyslÃ­kova','Na BojiÅ¡ti','Na FidlovaÄce',
  'Na Florenci','Na Folimance','Na HrÃ¡dku','Na Kleovce','Na KovÃ¡rnÄ›','Na KozaÄce',
  'Na KrÃ¡lovce','Na MorÃ¡ni','Na MÅ¯stku','Na OstrÅ¯vku','Na PÅ™Ã­kopÄ›','Na RybnÃ­Äku',
  'Na Å afrÃ¡nce','Na Slovanech','Na Slupi','Na Smetance','Na StrÃ¡ni','Na Å vihance',
  'Na VÃ­tÄ›znÃ© plÃ¡ni','Na ZÃ¡meckÃ©','Na ZboÅ™enci','Na Zderaze','Nad Petruskou',
  'NÃ¡rodnÃ­','NÃ¡rodnÃ­ tÅ™Ã­da','NavrÃ¡tilova','NekÃ¡zanka','Nezamyslova','NitranskÃ¡',
  'NorskÃ¡','NovgorodskÃ¡','NuselskÃ¡','ObloukovÃ¡','OdborÅ¯','OldÅ™ichova','Olivova',
  'OmladinÃ¡Å™Å¯','OndÅ™Ã­Äkova','OpatovickÃ¡','Opletalova','OrebitskÃ¡','OrelskÃ¡','OrlickÃ¡',
  'OstrovnÃ­','Otakarova','PalackÃ©ho','PanskÃ¡','PerlovÃ¡','PeruckÃ¡','Perunova',
  'Petra Rezka','PetrohradskÃ¡','Pod Karlovem','Pod NuselskÃ½mi schody','Pod Slovany',
  'Pod Stupni','Pod Terebkou','Pod VÄ›trovem','Pod VÃ½topnou','Pod ZvonaÅ™kou',
  'PolitickÃ½ch vÄ›zÅˆÅ¯','PolskÃ¡','PospÃ­Å¡ilova','PÅ™emyslovskÃ¡','PÅ™Ã­bÄ›nickÃ¡',
  'PÅ™ibyslavskÃ¡','PÅ™Ã­ÄnÃ¡','ProvaznickÃ¡','PrvnÃ­ho pluku','PurkyÅˆova','RadhoÅ¡Å¥skÃ¡',
  'Å˜ehoÅ™ova','Rejskova','Resslova','Å˜eznickÃ¡','Å˜Ã­mskÃ¡','Å˜ipskÃ¡','Rokycanova',
  'Rostislavova','RostovskÃ¡','RubeÅ¡ova','RumunskÃ¡','RuskÃ¡','RÅ¯Å¾ovÃ¡','Rybalkova',
  'Å afaÅ™Ã­kova','SalmovskÃ¡','SÃ¡mova','SarajevskÃ¡','SÃ¡zavskÃ¡','Seifertova','Sekaninova',
  'SenovÃ¡Å¾nÃ¡','SevastopolskÃ¡','Å evÄÃ­kova','Sezimova','Å kolskÃ¡','Å krÃ©tova','SlavÃ­kova',
  'SlezskÃ¡','SlovenskÃ¡','Å milovskÃ©ho','SmolenskÃ¡','SoboteckÃ¡','SokolskÃ¡','SpÃ¡lenÃ¡',
  'Å panÄ›lskÃ¡','SportovnÃ­','SpytihnÄ›vova','Å tÄ›pÃ¡nskÃ¡','Å tÃ­tnÃ©ho','StudniÄkova',
  'Å ubertova','Å umavskÃ¡','Svatoplukova','Svobodova','TÃ¡boritskÃ¡','TÃ¡borskÃ¡',
  'TÅ™ebÃ­zskÃ©ho','TrocnovskÃ¡','Trojanova','TrojickÃ¡','TyrÅ¡ova','U Bulhara','U Divadla',
  'U HavlÃ­ÄkovÃ½ch sadÅ¯','U HorskÃ© brÃ¡ny','U KanÃ¡lky','U Nemocnice','U PamÃ¡tnÃ­ku',
  'U PernÅ¡tejnskÃ½ch','U PÅ¯jÄovny','U RajskÃ© zahrady','U StarÃ© sokolovny','U TrÅ¾nice',
  'U Viktorie','U VodÃ¡rny','U VrÅ¡ovickÃ©ho nÃ¡draÅ¾Ã­','U ZvonaÅ™ky','UkrajinskÃ¡',
  'UruguayskÃ¡','V Celnici','V CÃ­pu','V JÃ¡mÄ›','V JirchÃ¡Å™Ã­ch','V TÅ¯nÃ­ch','VÃ¡clavskÃ¡',
  'VarÅ¡avskÃ¡','Ve SmeÄkÃ¡ch','VelehradskÃ¡','VÄ›trov','VinaÅ™ickÃ©ho','ViniÄnÃ¡',
  'VinohradskÃ¡','VÃ­ta NejedlÃ©ho','VladimÃ­rova','Vladislavova','Vlastislavova',
  'Vlkova','Vocelova','VodiÄkova','VoronÄ›Å¾skÃ¡','VotoÄkova','VozovÃ¡','VrÅ¡ovickÃ¡',
  'VyÅ¡ehradskÃ¡','Washingtonova','Wenzigova','Wilsonova','ZÃ¡hÅ™ebskÃ¡','Å½ateckÃ½ch',
  'ZÃ¡viÅ¡ova','Å½itnÃ¡','Å½itomÃ­rskÃ¡','ZvonaÅ™ova','Albertov','FÃ¼gnerovo nÃ¡mÄ›stÃ­',
  'I. P. Pavlova','Karlovo nÃ¡mÄ›stÃ­','KostnickÃ© nÃ¡mÄ›stÃ­','nÃ¡mÄ›stÃ­ BratÅ™Ã­ SynkÅ¯',
  'nÃ¡mÄ›stÃ­ GenerÃ¡la KutlvaÅ¡ra','nÃ¡mÄ›stÃ­ I. P. Pavlova','nÃ¡mÄ›stÃ­ JiÅ™Ã­ho z PodÄ›brad',
  'nÃ¡mÄ›stÃ­ MÃ­ru','OstrÄilovo nÃ¡mÄ›stÃ­','SenovÃ¡Å¾nÃ© nÃ¡mÄ›stÃ­','Å kroupovo nÃ¡mÄ›stÃ­',
  'SladkovskÃ©ho nÃ¡mÄ›stÃ­','Tylovo nÃ¡mÄ›stÃ­','VrÅ¡ovickÃ© nÃ¡mÄ›stÃ­','Å½iÅ¾kovo nÃ¡mÄ›stÃ­'
];
